name: PMD Static Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pmd-analysis:
    name: Run PMD Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Run PMD Analysis
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'java-basic'

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: pmd-report.xml
          retention-days: 7

      - name: Publish PMD Report in Summary
        run: |
          echo "## PMD Static Code Analysis Report" >> $GITHUB_STEP_SUMMARY
          echo "[Download PMD Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
